## Leitura dos dados

Carrega o arquivo CSV da PRF para um DataFrame com Pandas.

In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/datatran2026.csv",sep=";",encoding="latin1")

print(df.head())

         id data_inversa    dia_semana   horario  uf   br     km  municipio  \
0  742921.0   2026-01-01  quinta-feira  04:04:00  TO  153    155  ARAGUAINA
1  742942.0   2026-01-01  quinta-feira  06:40:00  MG  262  146,1  RIO CASCA
2  742943.0   2026-01-01  quinta-feira  06:58:00  SC  101    193    BIGUACU
3  742947.0   2026-01-01  quinta-feira  07:05:00  DF   60     23   BRASILIA
4  742960.0   2026-01-01  quinta-feira  06:17:00  MT  163   1044     MATUPA

                             causa_acidente                  tipo_acidente  \
0  Objeto estático sobre o leito carroçável                     Tombamento
1                         Condutor Dormindo                Colisão frontal
2  Reação tardia ou ineficiente do condutor  Colisão lateral mesmo sentido
3  Reação tardia ou ineficiente do condutor               Colisão traseira
4                    Transitar na contramão                Colisão frontal

   ... feridos_graves ilesos ignorados feridos veiculos      latitude  \
0  ...              0      1         3       0        5     -7,291548
1  ...              4      1         1       4        3   -20,0240733
2  ...              0      1         2       1        4  -27,48935222
3  ...              0      1         1       1        3    -15,988927
4  ...              1      1         3       1        5  -10,14330603

      longitude  regional  delegacia             uop
0    -48,286252   SPRF-TO   DEL02-TO  UOP01-DEL02-TO
1   -42,7422291   SPRF-MG   DEL03-MG  UOP03-DEL03-MG
2  -48,65565777   SPRF-SC   DEL01-SC  UOP01-DEL01-SC
3      -48,2263   SPRF-DF   DEL03-DF  UOP01-DEL03-DF
4  -54,93075559   SPRF-MT   DEL06-MT  UOP03-DEL06-MT

[5 rows x 30 columns]

## Dimensão da base

Mostra a quantidade de linhas e colunas do DataFrame.

In [19]:
df.shape

(48712, 30)

## Colunas da base

Exibe os nomes das colunas disponíveis no conjunto de dados.

In [ ]:
df.columns.tolist()

Index(['id', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km',
       'municipio', 'causa_acidente', 'tipo_acidente',
       'classificacao_acidente', 'fase_dia', 'sentido_via',
       'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo',
       'pessoas', 'mortos', 'feridos_leves', 'feridos_graves', 'ilesos',
       'ignorados', 'feridos', 'veiculos', 'latitude', 'longitude', 'regional',
       'delegacia', 'uop'],
      dtype='str')

## Informações da base

Mostra tipos das colunas, valores preenchidos e uso de memória.

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48712 entries, 0 to 48711
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      48712 non-null  float64
 1   data_inversa            48712 non-null  str
 2   dia_semana              48712 non-null  str
 3   horario                 48712 non-null  str
 4   uf                      48712 non-null  str
 5   br                      48712 non-null  int64
 6   km                      48712 non-null  str
 7   municipio               48712 non-null  str
 8   causa_acidente          48712 non-null  str
 9   tipo_acidente           48712 non-null  str
 10  classificacao_acidente  48711 non-null  str
 11  fase_dia                48712 non-null  str
 12  sentido_via             48712 non-null  str
 13  condicao_metereologica  48712 non-null  str
 14  tipo_pista              48712 non-null  str
 15  tracado_via             48712 non-null  str
 16  uso_solo                48712 non-null  str
 17  pessoas                 48712 non-null  int64
 18  mortos                  48712 non-null  int64
 19  feridos_leves           48712 non-null  int64
 20  feridos_graves          48712 non-null  int64
 21  ilesos                  48712 non-null  int64
 22  ignorados               48712 non-null  int64
 23  feridos                 48712 non-null  int64
 24  veiculos                48712 non-null  int64
 25  latitude                48712 non-null  str
 26  longitude               48712 non-null  str
 27  regional                48711 non-null  str
 28  delegacia               48700 non-null  str
 29  uop                     48686 non-null  str
dtypes: float64(1), int64(9), str(20)
memory usage: 21.2 MB

## Valores nulos

Conta quantos valores ausentes existem em cada coluna.

In [21]:
df.isnull().sum()

id                         0
data_inversa               0
dia_semana                 0
horario                    0
uf                         0
br                         0
km                         0
municipio                  0
causa_acidente             0
tipo_acidente              0
classificacao_acidente     1
fase_dia                   0
sentido_via                0
condicao_metereologica     0
tipo_pista                 0
tracado_via                0
uso_solo                   0
pessoas                    0
mortos                     0
feridos_leves              0
feridos_graves             0
ilesos                     0
ignorados                  0
feridos                    0
veiculos                   0
latitude                   0
longitude                  0
regional                   1
delegacia                 12
uop                       26
dtype: int64

## Registros duplicados

Verifica quantas linhas duplicadas existem na base.

In [22]:
df.duplicated().sum()

np.int64(0)

## Estatísticas descritivas

Mostra estatísticas básicas das colunas numéricas.}

In [24]:
df.describe()

,id,br,pessoas,mortos,feridos_leves,feridos_graves,ilesos,ignorados,feridos,veiculos
count,48712.000000,48712.000000,48712.000000,48712.000000,48712.000000,48712.000000,48712.000000,48712.000000,48712.000000,48712.000000
mean,769950.274162,210.702537,2.632185,0.084599,0.874979,0.275025,1.086632,0.399737,1.150004,2.009977
std,15464.256134,129.084581,2.282869,0.362937,1.069419,0.624355,1.855833,0.832486,1.202487,1.109948
min,742884.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,756598.750000,101.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
50%,769986.500000,163.000000,2.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,2.000000
75%,783329.250000,324.000000,3.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,2.000000
max,800593.000000,495.000000,88.000000,23.000000,40.000000,27.000000,85.000000,18.000000,48.000000,19.000000

## Acidentes por estado

Mostra quantos registros de acidentes existem em cada UF.

In [25]:
df["uf"].value_counts()

uf
MG    6307
SC    5600
PR    5267
RJ    4366
RS    3042
SP    2987
BA    2837
GO    2307
PE    2150
MT    1723
ES    1587
RO    1274
PB    1196
MS    1124
RN     986
PI     975
MA     899
PA     764
CE     755
DF     715
TO     517
AL     420
SE     400
AC     211
AM     119
AP     108
RR      76
Name: count, dtype: int64

## Municípios com mais registros

Exibe os municípios com maior quantidade de acidentes registrados.

In [26]:
df["municipio"].value_counts().head(10)

municipio
BRASILIA           715
DUQUE DE CAXIAS    571
SAO JOSE           520
BETIM              500
RECIFE             451
GUARULHOS          424
CURITIBA           407
PALHOCA            373
JOAO PESSOA        357
NOVA IGUACU        336
Name: count, dtype: int64

## Tipos de acidente

Mostra os tipos de acidentes mais registrados na base.

In [27]:
df["tipo_acidente"].value_counts()

tipo_acidente
Colisão traseira                  9854
Saída de leito carroçável         6941
Colisão transversal               6219
Colisão lateral mesmo sentido     5431
Tombamento                        4177
Colisão com objeto                3307
Colisão frontal                   3151
Queda de ocupante de veículo      2328
Atropelamento de Pedestre         1968
Colisão lateral sentido oposto    1467
Incêndio                          1197
Engavetamento                      893
Capotamento                        757
Atropelamento de Animal            752
Eventos atípicos                   197
Derramamento de carga               64
Sinistro pessoal de trânsito         9
Name: count, dtype: int64

## Causas dos acidentes

Exibe as causas de acidentes mais frequentes.

In [29]:
df["causa_acidente"].value_counts().head(10)

causa_acidente
Ausência de reação do condutor                               7798
Reação tardia ou ineficiente do condutor                     7407
Acessar a via sem observar a presença dos outros veículos    4767
Condutor deixou de manter distância do veículo da frente     3001
Manobra de mudança de faixa                                  2723
Velocidade Incompatível                                      2563
Ingestão de álcool pelo condutor                             2419
Demais falhas mecânicas ou elétricas                         2187
Transitar na contramão                                       1677
Condutor Dormindo                                            1277
Name: count, dtype: int64

## Acidentes por dia da semana

Mostra a quantidade de registros para cada dia da semana.

In [30]:
df["dia_semana"].value_counts()

dia_semana
domingo          7810
sábado           7666
sexta-feira      7543
segunda-feira    6791
quinta-feira     6629
quarta-feira     6222
terça-feira      6051
Name: count, dtype: int64

## Valores únicos

Mostra quantos valores diferentes existem em algumas colunas importantes.

In [31]:
print("UF:",df["uf"].nunique())
print("Municípios:", df["municipio"].nunique())
print("Tipos de acidente:", df["tipo_acidente"].nunique())
print("Causas: ",df["causa_acidente"].nunique())

UF: 27
Municípios: 1812
Tipos de acidente: 17
Causas:  69

## Conversão da data

Converte a coluna de data para o formato de data do Pandas.

In [32]:
df["data_inversa"] = pd.to_datetime(df["data_inversa"])

## Verificação do tipo da data

Confirma se a coluna foi convertida corretamente.

In [33]:
df["data_inversa"].dtype

dtype('<M8[us]')

## Extração do ano

Cria uma coluna com o ano do acidente a partir da data.

In [34]:
df["ano"] = df["data_inversa"].dt.year

## Extração do mês

Cria uma coluna com o mês do acidente.

In [35]:
df["mes"] = df["data_inversa"].dt.month

## Acidentes por mês

Mostra a quantidade de acidentes registrados em cada mês.

In [36]:
df["mes"].value_counts().sort_index()

mes
1    5825
2    5597
3    6137
4    5984
5    6312
6    6186
7    6290
8    6381
Name: count, dtype: int64

## Comparação das bases por ano

Carrega os arquivos de 2022 a 2026 para comparar a quantidade de linhas e colunas.

In [3]:
arquivos = {
    2022: "../data/raw/datatran2022.csv",
    2023: "../data/raw/datatran2023.csv",
    2024: "../data/raw/datatran2024.csv",
    2025: "../data/raw/datatran2025.csv",
    2026: "../data/raw/datatran2026.csv"
}

for ano, caminho in arquivos.items():
    df_ano = pd.read_csv(
        caminho,
        sep=";",
        encoding="latin1"
    )

    print(
        f"{ano} -> "
        f"{df_ano.shape[0]} linhas | "
        f"{df_ano.shape[1]} colunas"
    )

2022 -> 64606 linhas | 30 colunas
2023 -> 67766 linhas | 30 colunas
2024 -> 73202 linhas | 30 colunas
2025 -> 72529 linhas | 30 colunas
2026 -> 48712 linhas | 30 colunas

## Comparação das colunas

Verifica se os arquivos de todos os anos possuem a mesma estrutura de colunas.

In [4]:
for ano, caminho in arquivos.items():
    df_ano = pd.read_csv(
        caminho,
        sep=";",
        encoding="latin1"
    )

    print(f"\nAno: {ano}")
    print(df_ano.columns.tolist())

Ano: 2022
['id', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km', 'municipio', 'causa_acidente', 'tipo_acidente', 'classificacao_acidente', 'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo', 'pessoas', 'mortos', 'feridos_leves', 'feridos_graves', 'ilesos', 'ignorados', 'feridos', 'veiculos', 'latitude', 'longitude', 'regional', 'delegacia', 'uop']

Ano: 2023
['id', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km', 'municipio', 'causa_acidente', 'tipo_acidente', 'classificacao_acidente', 'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo', 'pessoas', 'mortos', 'feridos_leves', 'feridos_graves', 'ilesos', 'ignorados', 'feridos', 'veiculos', 'latitude', 'longitude', 'regional', 'delegacia', 'uop']

Ano: 2024
['id', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km', 'municipio', 'causa_acidente', 'tipo_acidente', 'classificacao_acidente', 'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo', 'pessoas', 'mortos', 'feridos_leves', 'feridos_graves', 'ilesos', 'ignorados', 'feridos', 'veiculos', 'latitude', 'longitude', 'regional', 'delegacia', 'uop']

Ano: 2025
['id', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km', 'municipio', 'causa_acidente', 'tipo_acidente', 'classificacao_acidente', 'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo', 'pessoas', 'mortos', 'feridos_leves', 'feridos_graves', 'ilesos', 'ignorados', 'feridos', 'veiculos', 'latitude', 'longitude', 'regional', 'delegacia', 'uop']

Ano: 2026
['id', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km', 'municipio', 'causa_acidente', 'tipo_acidente', 'classificacao_acidente', 'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo', 'pessoas', 'mortos', 'feridos_leves', 'feridos_graves', 'ilesos', 'ignorados', 'feridos', 'veiculos', 'latitude', 'longitude', 'regional', 'delegacia', 'uop']

## Validação da estrutura das bases

Compara as colunas de cada ano com a estrutura da base de 2026.

In [5]:
colunas_referencia = df.columns.tolist()

for ano, caminho in arquivos.items():
    df_ano = pd.read_csv(
        caminho,
        sep=";",
        encoding="latin1"
    )

    estrutura_igual = df_ano.columns.tolist() == colunas_referencia

    print(f"{ano} -> estrutura igual a 2026: {estrutura_igual}")

2022 -> estrutura igual a 2026: True
2023 -> estrutura igual a 2026: True
2024 -> estrutura igual a 2026: True
2025 -> estrutura igual a 2026: True
2026 -> estrutura igual a 2026: True


## Comparação dos tipos de dados

Verifica os tipos das colunas em cada base anual.

In [6]:
for ano, caminho in arquivos.items():
    df_ano = pd.read_csv(
        caminho,
        sep=";",
        encoding="latin1"
    )

    print(f"\nAno: {ano}")
    print(df_ano.dtypes)

Ano: 2022
id                        int64
data_inversa                str
dia_semana                  str
horario                     str
uf                          str
br                        int64
km                          str
municipio                   str
causa_acidente              str
tipo_acidente               str
classificacao_acidente      str
fase_dia                    str
sentido_via                 str
condicao_metereologica      str
tipo_pista                  str
tracado_via                 str
uso_solo                    str
pessoas                   int64
mortos                    int64
feridos_leves             int64
feridos_graves            int64
ilesos                    int64
ignorados                 int64
feridos                   int64
veiculos                  int64
latitude                    str
longitude                   str
regional                    str
delegacia                   str
uop                         str
dtype: object

Ano: 2023
id                        int64
data_inversa                str
dia_semana                  str
horario                     str
uf                          str
br                        int64
km                          str
municipio                   str
causa_acidente              str
tipo_acidente               str
classificacao_acidente      str
fase_dia                    str
sentido_via                 str
condicao_metereologica      str
tipo_pista                  str
tracado_via                 str
uso_solo                    str
pessoas                   int64
mortos                    int64
feridos_leves             int64
feridos_graves            int64
ilesos                    int64
ignorados                 int64
feridos                   int64
veiculos                  int64
latitude                    str
longitude                   str
regional                    str
delegacia                   str
uop                         str
dtype: object

Ano: 2024
id                        float64
data_inversa                  str
dia_semana                    str
horario                       str
uf                            str
br                          int64
km                            str
municipio                     str
causa_acidente                str
tipo_acidente                 str
classificacao_acidente        str
fase_dia                      str
sentido_via                   str
condicao_metereologica        str
tipo_pista                    str
tracado_via                   str
uso_solo                      str
pessoas                     int64
mortos                      int64
feridos_leves               int64
feridos_graves              int64
ilesos                      int64
ignorados                   int64
feridos                     int64
veiculos                    int64
latitude                      str
longitude                     str
regional                      str
delegacia                     str
uop                           str
dtype: object

Ano: 2025
id                        int64
data_inversa                str
dia_semana                  str
horario                     str
uf                          str
br                        int64
km                          str
municipio                   str
causa_acidente              str
tipo_acidente               str
classificacao_acidente      str
fase_dia                    str
sentido_via                 str
condicao_metereologica      str
tipo_pista                  str
tracado_via                 str
uso_solo                    str
pessoas                   int64
mortos                    int64
feridos_leves             int64
feridos_graves            int64
ilesos                    int64
ignorados                 int64
feridos                   int64
veiculos                  int64
latitude                    str
longitude                   str
regional                    str
delegacia                   str
uop                         str
dtype: object

Ano: 2026
id                        float64
data_inversa                  str
dia_semana                    str
horario                       str
uf                            str
br                          int64
km                            str
municipio                     str
causa_acidente                str
tipo_acidente                 str
classificacao_acidente        str
fase_dia                      str
sentido_via                   str
condicao_metereologica        str
tipo_pista                    str
tracado_via                   str
uso_solo                      str
pessoas                     int64
mortos                      int64
feridos_leves               int64
feridos_graves              int64
ilesos                      int64
ignorados                   int64
feridos                     int64
veiculos                    int64
latitude                      str
longitude                     str
regional                      str
delegacia                     str
uop                           str
dtype: object

## Comparação automática dos tipos

Compara os tipos de dados de cada ano com a base de 2026.

In [7]:
tipos_referencia = df.dtypes

for ano, caminho in arquivos.items():
    df_ano = pd.read_csv(
        caminho,
        sep=";",
        encoding="latin1"
    )

    diferencas = df_ano.dtypes[df_ano.dtypes != tipos_referencia]

    print(f"\nAno: {ano}")

    if diferencas.empty:
        print("Tipos iguais à base de 2026")
    else:
        print("Colunas com tipos diferentes:")
        print(diferencas)

Ano: 2022
Colunas com tipos diferentes:
id    int64
dtype: object

Ano: 2023
Colunas com tipos diferentes:
id    int64
dtype: object

Ano: 2024
Tipos iguais à base de 2026

Ano: 2025
Colunas com tipos diferentes:
id    int64
dtype: object

Ano: 2026
Tipos iguais à base de 2026

## Resumo da qualidade das bases

Cria uma tabela com a quantidade de linhas, colunas, valores nulos e registros duplicados de cada ano.

In [8]:
resumo = []

for ano, caminho in arquivos.items():
    df_ano = pd.read_csv(
        caminho,
        sep=";",
        encoding="latin1"
    )

    resumo.append({
        "ano": ano,
        "linhas": df_ano.shape[0],
        "colunas": df_ano.shape[1],
        "nulos": df_ano.isnull().sum().sum(),
        "duplicados": df_ano.duplicated().sum()
    })

resumo_df = pd.DataFrame(resumo)

resumo_df

    ano  linhas  colunas  nulos  duplicados
0  2022   64606       30     75           0
1  2023   67766       30     96           0
2  2024   73202       30    109           0
3  2025   72529       30     63           0
4  2026   48712       30     40           0

## Valores nulos por coluna e por ano

Identifica em quais colunas existem valores ausentes em cada base anual.

In [9]:
for ano, caminho in arquivos.items():
    df_ano = pd.read_csv(
        caminho,
        sep=";",
        encoding="latin1"
    )

    nulos = df_ano.isnull().sum()
    nulos = nulos[nulos > 0]

    print(f"\nAno: {ano}")

    if nulos.empty:
        print("Nenhum valor nulo encontrado.")
    else:
        print(nulos)

Ano: 2022
classificacao_acidente     1
regional                   5
delegacia                 19
uop                       50
dtype: int64

Ano: 2023
classificacao_acidente     1
regional                  17
delegacia                 32
uop                       46
dtype: int64

Ano: 2024
classificacao_acidente     1
delegacia                 37
uop                       71
dtype: int64

Ano: 2025
classificacao_acidente     1
regional                   2
delegacia                 22
uop                       38
dtype: int64

Ano: 2026
classificacao_acidente     1
regional                   1
delegacia                 12
uop                       26
dtype: int64

## Registros sem classificação do acidente

Exibe os registros que não possuem valor na coluna de classificação do acidente.

In [10]:
for ano, caminho in arquivos.items():
    df_ano = pd.read_csv(
        caminho,
        sep=";",
        encoding="latin1"
    )

    faltantes = df_ano[
        df_ano["classificacao_acidente"].isnull()
    ]

    if not faltantes.empty:
        print(f"\nAno: {ano}")
        print(
            faltantes[
                [
                    "id",
                    "data_inversa",
                    "uf",
                    "municipio",
                    "tipo_acidente",
                    "classificacao_acidente"
                ]
            ]
        )

Ano: 2022
       id data_inversa  uf    municipio     tipo_acidente  \
0  405151   2022-01-01  PI  MARCOLANDIA  Colisão traseira

  classificacao_acidente
0                    NaN

Ano: 2023
       id data_inversa  uf          municipio tipo_acidente  \
2  496590   2023-01-01  MT  GUARANTA DO NORTE    Tombamento

  classificacao_acidente
2                    NaN

Ano: 2024
         id data_inversa  uf           municipio  \
0  571789.0   2024-01-01  ES  CONCEICAO DA BARRA

                    tipo_acidente classificacao_acidente
0  Colisão lateral sentido oposto                    NaN

Ano: 2025
       id data_inversa  uf  municipio    tipo_acidente classificacao_acidente
1  652519   2025-01-01  CE  PENAFORTE  Colisão frontal                    NaN

Ano: 2026
         id data_inversa  uf  municipio tipo_acidente classificacao_acidente
0  742921.0   2026-01-01  TO  ARAGUAINA    Tombamento                    NaN

## Tratamento da classificação ausente

Substitui valores nulos da classificação do acidente por "Não informado", preservando o restante do registro.

In [11]:
df["classificacao_acidente"] = (
    df["classificacao_acidente"]
    .fillna("Não informado")
)

## Relação entre campos administrativos ausentes

Verifica se os valores nulos de regional, delegacia e UOP aparecem nos mesmos registros.

In [12]:
for ano, caminho in arquivos.items():
    df_ano = pd.read_csv(
        caminho,
        sep=";",
        encoding="latin1"
    )

    administrativos_nulos = df_ano[
        df_ano[["regional", "delegacia", "uop"]]
        .isnull()
        .any(axis=1)
    ]

    print(
        f"{ano} -> "
        f"{len(administrativos_nulos)} registros "
        f"com algum campo administrativo ausente"
    )

2022 -> 50 registros com algum campo administrativo ausente
2023 -> 46 registros com algum campo administrativo ausente
2024 -> 71 registros com algum campo administrativo ausente
2025 -> 38 registros com algum campo administrativo ausente
2026 -> 26 registros com algum campo administrativo ausente

## Padrão dos campos administrativos ausentes

Mostra quais combinações de campos administrativos estão nulas em cada ano.

In [13]:
for ano, caminho in arquivos.items():
    df_ano = pd.read_csv(
        caminho,
        sep=";",
        encoding="latin1"
    )

    padrao_nulos = (
        df_ano[["regional", "delegacia", "uop"]]
        .isnull()
        .value_counts()
    )

    print(f"\nAno: {ano}")
    print(padrao_nulos)

Ano: 2022
regional  delegacia  uop
False     False      False    64556
                     True        31
          True       True        14
True      True       True         5
Name: count, dtype: int64

Ano: 2023
regional  delegacia  uop
False     False      False    67720
True      True       True        17
False     True       True        15
          False      True        14
Name: count, dtype: int64

Ano: 2024
regional  delegacia  uop
False     False      False    73131
          True       True        37
          False      True        34
Name: count, dtype: int64

Ano: 2025
regional  delegacia  uop
False     False      False    72491
          True       True        20
          False      True        16
True      True       True         2
Name: count, dtype: int64

Ano: 2026
regional  delegacia  uop
False     False      False    48686
                     True        14
          True       True        11
True      True       True         1
Name: count, dtype: int64

## Tratamento dos campos administrativos

Substitui valores nulos de regional, delegacia e UOP por "Não informado".

In [14]:
colunas_administrativas = [
    "regional",
    "delegacia",
    "uop"
]

df[colunas_administrativas] = (
    df[colunas_administrativas]
    .fillna("Não informado")
)

## Função de limpeza

Cria uma função para aplicar as mesmas regras de tratamento em todas as bases.

In [15]:
def limpar_dados(df):
    df = df.copy()

    df["classificacao_acidente"] = (
        df["classificacao_acidente"]
        .fillna("Não informado")
    )

    colunas_administrativas = [
        "regional",
        "delegacia",
        "uop"
    ]

    df[colunas_administrativas] = (
        df[colunas_administrativas]
        .fillna("Não informado")
    )

    return df

## Tratamento dos valores nulos

Substitui valores ausentes da classificação e dos campos administrativos por "Não informado".

In [16]:
df["classificacao_acidente"] = (
    df["classificacao_acidente"]
    .fillna("Não informado")
)

colunas_administrativas = [
    "regional",
    "delegacia",
    "uop"
]

df[colunas_administrativas] = (
    df[colunas_administrativas]
    .fillna("Não informado")
)

## Função de limpeza

Cria uma função para aplicar as mesmas regras de limpeza em todas as bases.

In [18]:
def limpar_dados(df):
    df = df.copy()

    df["classificacao_acidente"] = (
        df["classificacao_acidente"]
        .fillna("Não informado")
    )

    colunas_administrativas = [
        "regional",
        "delegacia",
        "uop"
    ]

    df[colunas_administrativas] = (
        df[colunas_administrativas]
        .fillna("Não informado")
    )

    return df

## Padronização dos tipos de dados

Converte datas e campos numéricos para tipos adequados antes da união das bases.

In [19]:
def limpar_dados(df):
    df = df.copy()

    # Tratamento dos valores nulos
    df["classificacao_acidente"] = (
        df["classificacao_acidente"]
        .fillna("Não informado")
    )

    colunas_administrativas = [
        "regional",
        "delegacia",
        "uop"
    ]

    df[colunas_administrativas] = (
        df[colunas_administrativas]
        .fillna("Não informado")
    )

    # Padronização do ID
    df["id"] = df["id"].astype("Int64")

    # Conversão da data
    df["data_inversa"] = pd.to_datetime(
        df["data_inversa"],
        errors="coerce"
    )

    # Conversão do KM
    df["km"] = (
        df["km"]
        .astype(str)
        .str.replace(",", ".", regex=False)
    )

    df["km"] = pd.to_numeric(
        df["km"],
        errors="coerce"
    )

    # Conversão de latitude e longitude
    for coluna in ["latitude", "longitude"]:
        df[coluna] = (
            df[coluna]
            .astype(str)
            .str.replace(",", ".", regex=False)
        )

        df[coluna] = pd.to_numeric(
            df[coluna],
            errors="coerce"
        )

    return df

## Teste da função de limpeza

Aplica a função na base de 2026 para validar as transformações.

In [20]:
df_2026_teste = pd.read_csv(
    arquivos[2026],
    sep=";",
    encoding="latin1"
)

df_2026_teste = limpar_dados(df_2026_teste)

df_2026_teste[
    [
        "id",
        "data_inversa",
        "km",
        "latitude",
        "longitude"
    ]
].dtypes

id                       Int64
data_inversa    datetime64[us]
km                     float64
latitude               float64
longitude              float64
dtype: object

## Verificação das conversões

Exibe alguns registros após a padronização dos tipos.

In [22]:
df_2026_teste[
    [
        "id",
        "data_inversa",
        "km",
        "latitude",
        "longitude"
    ]
].head()

       id data_inversa      km   latitude  longitude
0  742921   2026-01-01   155.0  -7.291548 -48.286252
1  742942   2026-01-01   146.1 -20.024073 -42.742229
2  742943   2026-01-01   193.0 -27.489352 -48.655658
3  742947   2026-01-01    23.0 -15.988927 -48.226300
4  742960   2026-01-01  1044.0 -10.143306 -54.930756

## Validação das conversões em todas as bases

Aplica a função de limpeza em todos os anos e verifica se as conversões geraram valores nulos.

In [23]:
colunas_convertidas = [
    "id",
    "data_inversa",
    "km",
    "latitude",
    "longitude"
]

for ano, caminho in arquivos.items():
    df_ano = pd.read_csv(
        caminho,
        sep=";",
        encoding="latin1"
    )

    df_ano = limpar_dados(df_ano)

    print(f"\nAno: {ano}")
    print(df_ano[colunas_convertidas].isnull().sum())

Ano: 2022
id              0
data_inversa    0
km              0
latitude        0
longitude       0
dtype: int64

Ano: 2023
id              0
data_inversa    0
km              0
latitude        0
longitude       0
dtype: int64

Ano: 2024
id              0
data_inversa    0
km              0
latitude        0
longitude       0
dtype: int64

Ano: 2025
id              0
data_inversa    0
km              0
latitude        0
longitude       0
dtype: int64

Ano: 2026
id              0
data_inversa    0
km              0
latitude        0
longitude       0
dtype: int64

## Registros com falha nas conversões

Conta quantos registros possuem valores ausentes nos campos numéricos e geográficos após a conversão.

In [24]:
for ano, caminho in arquivos.items():
    df_ano = pd.read_csv(
        caminho,
        sep=";",
        encoding="latin1"
    )

    df_ano = limpar_dados(df_ano)

    problemas = df_ano[
        df_ano[
            ["km", "latitude", "longitude"]
        ].isnull().any(axis=1)
    ]

    print(
        f"{ano} -> "
        f"{len(problemas)} registros com problema de conversão"
    )

2022 -> 0 registros com problema de conversão
2023 -> 0 registros com problema de conversão
2024 -> 0 registros com problema de conversão
2025 -> 0 registros com problema de conversão
2026 -> 0 registros com problema de conversão

## União das bases

Aplica a limpeza em todos os anos e reúne as bases de 2022 a 2026 em um único DataFrame.

In [25]:
bases_processadas = []

for ano, caminho in arquivos.items():
    df_ano = pd.read_csv(
        caminho,
        sep=";",
        encoding="latin1"
    )

    df_ano = limpar_dados(df_ano)

    bases_processadas.append(df_ano)

df_prf = pd.concat(
    bases_processadas,
    ignore_index=True
)

## Dimensão da base unificada

Verifica a quantidade total de registros e colunas após a união das bases.

In [26]:
df_prf.shape

(326815, 30)

## Verificação dos anos

Confirma se todos os anos estão presentes na base unificada.

In [27]:
df_prf["data_inversa"].dt.year.value_counts().sort_index()

data_inversa
2022    64606
2023    67766
2024    73202
2025    72529
2026    48712
Name: count, dtype: int64

## Validação dos valores nulos

Verifica se ainda existem valores ausentes após o processo de limpeza.

In [28]:
df_prf.isnull().sum()[df_prf.isnull().sum() > 0]

Series([], dtype: int64)

## Validação de duplicados

Verifica se a união das bases gerou registros duplicados.

In [30]:
df_prf.duplicated().sum()

np.int64(0)

## Validação dos identificadores

Verifica se existem IDs repetidos na base histórica.

In [31]:
df_prf["id"].duplicated().sum()

np.int64(0)

## Validação de IDs duplicados

Verifica se existem identificadores repetidos na base histórica.

In [32]:
df_prf["id"].duplicated().sum()

np.int64(0)

## Salvando a base processada

Salva a base unificada e limpa para uso nas próximas etapas do projeto.

In [33]:
df_prf.to_parquet(
    "../data/processed/prf_2022_2026.parquet",
    index=False
)